<template>
  <div class="page-shell"><section class="page-panel table-panel"><div class="toolbar table-toolbar"><div><div class="section-title">管理员管理</div><p>维护后台管理员账号、姓名、密码、等级和启用状态</p></div><div class="toolbar-actions"><el-input v-model="keyword" class="search-input" placeholder="搜索账号或姓名" clearable :prefix-icon="Search" @keyup.enter="fetch" @clear="fetch" /><el-button :icon="Refresh" @click="fetch">刷新</el-button><el-button type="primary" :icon="Plus" @click="openDialog()">新增管理员</el-button></div></div><el-table :data="tableData" v-loading="loading" stripe><el-table-column prop="username" label="账号" width="150" /><el-table-column prop="realName" label="姓名" width="140" /><el-table-column label="等级" width="120"><template #default="{ row }"><el-tag :type="row.role === 'SUPER_ADMIN' ? 'danger' : 'info'">{{ roleText(row.role) }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 1 ? 'success' : 'danger'">{{ row.status === 1 ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button size="small" type="primary" link :icon="Edit" @click="openDialog(row)">编辑</el-button><el-button size="small" type="danger" link :icon="Delete" @click="doDelete(row.id)">删除</el-button></template></el-table-column></el-table><div class="pager-wrap"><el-pagination v-model:current-page="current" v-model:page-size="size" :page-sizes="[5,10,20]" :total="total" layout="total, sizes, prev, pager, next" @size-change="fetch" @current-change="fetch" /></div></section><el-dialog v-model="dialogVisible" :title="isEdit ? '编辑管理员' : '新增管理员'" width="520px"><el-form ref="formRef" :model="form" :rules="rules" label-width="86px"><el-form-item label="账号" prop="username"><el-input v-model="form.username" /></el-form-item><el-form-item label="密码" prop="password"><el-input v-model="form.password" show-password /></el-form-item><el-form-item label="姓名" prop="realName"><el-input v-model="form.realName" /></el-form-item><el-form-item label="等级"><el-select v-model="form.role" class="full-control"><el-option label="系统管理员" value="SUPER_ADMIN" /><el-option label="普通管理员" value="ADMIN" /></el-select></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="doSave">保存</el-button></template></el-dialog></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { Delete, Edit, Plus, Refresh, Search } from '@element-plus/icons-vue'; import { addAdmin, deleteAdmin, getAdmins, updateAdmin } from '@/api'
const loading=ref(false), tableData=ref([]), current=ref(1), size=ref(10), total=ref(0), keyword=ref(''), dialogVisible=ref(false), isEdit=ref(false), formRef=ref(); const defaultForm=()=>({id:null,username:'',password:'',realName:'',role:'ADMIN',status:1}); const form=reactive(defaultForm()); const rules={username:[{required:true,message:'请输入账号',trigger:'blur'}],password:[{required:true,message:'请输入密码',trigger:'blur'}],realName:[{required:true,message:'请输入姓名',trigger:'blur'}]}
async function fetch(){loading.value=true;try{const res=await getAdmins({current:current.value,size:size.value,keyword:keyword.value});tableData.value=res.data.records||[];total.value=res.data.total||0}finally{loading.value=false}}
function openDialog(row){isEdit.value=!!row;Object.assign(form,row?{...row}:defaultForm());dialogVisible.value=true}
async function doSave(){const valid=await formRef.value.validate().catch(()=>false);if(!valid)return;if(isEdit.value){await updateAdmin({...form});ElMessage.success('修改成功')}else{await addAdmin({...form});ElMessage.success('新增成功')}dialogVisible.value=false;fetch()}
async function doDelete(id){await ElMessageBox.confirm('确定删除这个管理员吗？','提示',{type:'warning'});await deleteAdmin(id);ElMessage.success('删除成功');fetch()}
function roleText(role){return role==='SUPER_ADMIN'?'系统管理员':'普通管理员'}
onMounted(fetch)
</script>
<style scoped>.table-panel{padding:22px}.table-toolbar{margin-bottom:18px}.table-toolbar p{margin-top:6px;color:#6b7280}.toolbar-actions{display:flex;gap:10px;flex-wrap:wrap}.search-input{width:250px}.full-control{width:100%}.pager-wrap{display:flex;justify-content:flex-end;margin-top:18px}</style>
